// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.1
// source: grSim_Commands.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrSim_Robot_Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Kickspeedx    *float32               `protobuf:"fixed32,2,req,name=kickspeedx" json:"kickspeedx,omitempty"`
	Kickspeedz    *float32               `protobuf:"fixed32,3,req,name=kickspeedz" json:"kickspeedz,omitempty"`
	Veltangent    *float32               `protobuf:"fixed32,4,req,name=veltangent" json:"veltangent,omitempty"`
	Velnormal     *float32               `protobuf:"fixed32,5,req,name=velnormal" json:"velnormal,omitempty"`
	Velangular    *float32               `protobuf:"fixed32,6,req,name=velangular" json:"velangular,omitempty"`
	Spinner       *bool                  `protobuf:"varint,7,req,name=spinner" json:"spinner,omitempty"`
	Wheelsspeed   *bool                  `protobuf:"varint,8,req,name=wheelsspeed" json:"wheelsspeed,omitempty"`
	Wheel1        *float32               `protobuf:"fixed32,9,opt,name=wheel1" json:"wheel1,omitempty"`
	Wheel2        *float32               `protobuf:"fixed32,10,opt,name=wheel2" json:"wheel2,omitempty"`
	Wheel3        *float32               `protobuf:"fixed32,11,opt,name=wheel3" json:"wheel3,omitempty"`
	Wheel4        *float32               `protobuf:"fixed32,12,opt,name=wheel4" json:"wheel4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrSim_Robot_Command) Reset() {
	*x = GrSim_Robot_Command{}
	mi := &file_grSim_Commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrSim_Robot_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrSim_Robot_Command) ProtoMessage() {}

func (x *GrSim_Robot_Command) ProtoReflect() protoreflect.Message {
	mi := &file_grSim_Commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrSim_Robot_Command.ProtoReflect.Descriptor instead.
func (*GrSim_Robot_Command) Descriptor() ([]byte, []int) {
	return file_grSim_Commands_proto_rawDescGZIP(), []int{0}
}

func (x *GrSim_Robot_Command) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GrSim_Robot_Command) GetKickspeedx() float32 {
	if x != nil && x.Kickspeedx != nil {
		return *x.Kickspeedx
	}
	return 0
}

func (x *GrSim_Robot_Command) GetKickspeedz() float32 {
	if x != nil && x.Kickspeedz != nil {
		return *x.Kickspeedz
	}
	return 0
}

func (x *GrSim_Robot_Command) GetVeltangent() float32 {
	if x != nil && x.Veltangent != nil {
		return *x.Veltangent
	}
	return 0
}

func (x *GrSim_Robot_Command) GetVelnormal() float32 {
	if x != nil && x.Velnormal != nil {
		return *x.Velnormal
	}
	return 0
}

func (x *GrSim_Robot_Command) GetVelangular() float32 {
	if x != nil && x.Velangular != nil {
		return *x.Velangular
	}
	return 0
}

func (x *GrSim_Robot_Command) GetSpinner() bool {
	if x != nil && x.Spinner != nil {
		return *x.Spinner
	}
	return false
}

func (x *GrSim_Robot_Command) GetWheelsspeed() bool {
	if x != nil && x.Wheelsspeed != nil {
		return *x.Wheelsspeed
	}
	return false
}

func (x *GrSim_Robot_Command) GetWheel1() float32 {
	if x != nil && x.Wheel1 != nil {
		return *x.Wheel1
	}
	return 0
}

func (x *GrSim_Robot_Command) GetWheel2() float32 {
	if x != nil && x.Wheel2 != nil {
		return *x.Wheel2
	}
	return 0
}

func (x *GrSim_Robot_Command) GetWheel3() float32 {
	if x != nil && x.Wheel3 != nil {
		return *x.Wheel3
	}
	return 0
}

func (x *GrSim_Robot_Command) GetWheel4() float32 {
	if x != nil && x.Wheel4 != nil {
		return *x.Wheel4
	}
	return 0
}

type GrSim_Commands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *float64               `protobuf:"fixed64,1,req,name=timestamp" json:"timestamp,omitempty"`
	Isteamyellow  *bool                  `protobuf:"varint,2,req,name=isteamyellow" json:"isteamyellow,omitempty"`
	RobotCommands []*GrSim_Robot_Command `protobuf:"bytes,3,rep,name=robot_commands,json=robotCommands" json:"robot_commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrSim_Commands) Reset() {
	*x = GrSim_Commands{}
	mi := &file_grSim_Commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrSim_Commands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrSim_Commands) ProtoMessage() {}

func (x *GrSim_Commands) ProtoReflect() protoreflect.Message {
	mi := &file_grSim_Commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrSim_Commands.ProtoReflect.Descriptor instead.
func (*GrSim_Commands) Descriptor() ([]byte, []int) {
	return file_grSim_Commands_proto_rawDescGZIP(), []int{1}
}

func (x *GrSim_Commands) GetTimestamp() float64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *GrSim_Commands) GetIsteamyellow() bool {
	if x != nil && x.Isteamyellow != nil {
		return *x.Isteamyellow
	}
	return false
}

func (x *GrSim_Commands) GetRobotCommands() []*GrSim_Robot_Command {
	if x != nil {
		return x.RobotCommands
	}
	return nil
}

var File_grSim_Commands_proto protoreflect.FileDescriptor

const file_grSim_Commands_proto_rawDesc = "" +
	"\n" +
	"\x14grSim_Commands.proto\"\xdf\x02\n" +
	"\x13grSim_Robot_Command\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x1e\n" +
	"\n" +
	"kickspeedx\x18\x02 \x02(\x02R\n" +
	"kickspeedx\x12\x1e\n" +
	"\n" +
	"kickspeedz\x18\x03 \x02(\x02R\n" +
	"kickspeedz\x12\x1e\n" +
	"\n" +
	"veltangent\x18\x04 \x02(\x02R\n" +
	"veltangent\x12\x1c\n" +
	"\tvelnormal\x18\x05 \x02(\x02R\tvelnormal\x12\x1e\n" +
	"\n" +
	"velangular\x18\x06 \x02(\x02R\n" +
	"velangular\x12\x18\n" +
	"\aspinner\x18\a \x02(\bR\aspinner\x12 \n" +
	"\vwheelsspeed\x18\b \x02(\bR\vwheelsspeed\x12\x16\n" +
	"\x06wheel1\x18\t \x01(\x02R\x06wheel1\x12\x16\n" +
	"\x06wheel2\x18\n" +
	" \x01(\x02R\x06wheel2\x12\x16\n" +
	"\x06wheel3\x18\v \x01(\x02R\x06wheel3\x12\x16\n" +
	"\x06wheel4\x18\f \x01(\x02R\x06wheel4\"\x8f\x01\n" +
	"\x0egrSim_Commands\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x02(\x01R\ttimestamp\x12\"\n" +
	"\fisteamyellow\x18\x02 \x02(\bR\fisteamyellow\x12;\n" +
	"\x0erobot_commands\x18\x03 \x03(\v2\x14.grSim_Robot_CommandR\rrobotCommandsB-Z+github.com/Rione-SSL/RACOON-Pi/proto/pb_gen"

var (
	file_grSim_Commands_proto_rawDescOnce sync.Once
	file_grSim_Commands_proto_rawDescData []byte
)

func file_grSim_Commands_proto_rawDescGZIP() []byte {
	file_grSim_Commands_proto_rawDescOnce.Do(func() {
		file_grSim_Commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grSim_Commands_proto_rawDesc), len(file_grSim_Commands_proto_rawDesc)))
	})
	return file_grSim_Commands_proto_rawDescData
}

var file_grSim_Commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grSim_Commands_proto_goTypes = []any{
	(*GrSim_Robot_Command)(nil), // 0: grSim_Robot_Command
	(*GrSim_Commands)(nil),      // 1: grSim_Commands
}
var file_grSim_Commands_proto_depIdxs = []int32{
	0, // 0: grSim_Commands.robot_commands:type_name -> grSim_Robot_Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grSim_Commands_proto_init() }
func file_grSim_Commands_proto_init() {
	if File_grSim_Commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grSim_Commands_proto_rawDesc), len(file_grSim_Commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grSim_Commands_proto_goTypes,
		DependencyIndexes: file_grSim_Commands_proto_depIdxs,
		MessageInfos:      file_grSim_Commands_proto_msgTypes,
	}.Build()
	File_grSim_Commands_proto = out.File
	file_grSim_Commands_proto_goTypes = nil
	file_grSim_Commands_proto_depIdxs = nil
}
