// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.1
// source: grSim_Packet.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrSim_Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      *GrSim_Commands        `protobuf:"bytes,1,opt,name=commands" json:"commands,omitempty"`
	Replacement   *GrSim_Replacement     `protobuf:"bytes,2,opt,name=replacement" json:"replacement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrSim_Packet) Reset() {
	*x = GrSim_Packet{}
	mi := &file_grSim_Packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrSim_Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrSim_Packet) ProtoMessage() {}

func (x *GrSim_Packet) ProtoReflect() protoreflect.Message {
	mi := &file_grSim_Packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrSim_Packet.ProtoReflect.Descriptor instead.
func (*GrSim_Packet) Descriptor() ([]byte, []int) {
	return file_grSim_Packet_proto_rawDescGZIP(), []int{0}
}

func (x *GrSim_Packet) GetCommands() *GrSim_Commands {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *GrSim_Packet) GetReplacement() *GrSim_Replacement {
	if x != nil {
		return x.Replacement
	}
	return nil
}

var File_grSim_Packet_proto protoreflect.FileDescriptor

const file_grSim_Packet_proto_rawDesc = "" +
	"\n" +
	"\x12grSim_Packet.proto\x1a\x14grSim_Commands.proto\x1a\x17grSim_Replacement.proto\"q\n" +
	"\fgrSim_Packet\x12+\n" +
	"\bcommands\x18\x01 \x01(\v2\x0f.grSim_CommandsR\bcommands\x124\n" +
	"\vreplacement\x18\x02 \x01(\v2\x12.grSim_ReplacementR\vreplacementB-Z+github.com/Rione-SSL/RACOON-Pi/proto/pb_gen"

var (
	file_grSim_Packet_proto_rawDescOnce sync.Once
	file_grSim_Packet_proto_rawDescData []byte
)

func file_grSim_Packet_proto_rawDescGZIP() []byte {
	file_grSim_Packet_proto_rawDescOnce.Do(func() {
		file_grSim_Packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grSim_Packet_proto_rawDesc), len(file_grSim_Packet_proto_rawDesc)))
	})
	return file_grSim_Packet_proto_rawDescData
}

var file_grSim_Packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grSim_Packet_proto_goTypes = []any{
	(*GrSim_Packet)(nil),      // 0: grSim_Packet
	(*GrSim_Commands)(nil),    // 1: grSim_Commands
	(*GrSim_Replacement)(nil), // 2: grSim_Replacement
}
var file_grSim_Packet_proto_depIdxs = []int32{
	1, // 0: grSim_Packet.commands:type_name -> grSim_Commands
	2, // 1: grSim_Packet.replacement:type_name -> grSim_Replacement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grSim_Packet_proto_init() }
func file_grSim_Packet_proto_init() {
	if File_grSim_Packet_proto != nil {
		return
	}
	file_grSim_Commands_proto_init()
	file_grSim_Replacement_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grSim_Packet_proto_rawDesc), len(file_grSim_Packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grSim_Packet_proto_goTypes,
		DependencyIndexes: file_grSim_Packet_proto_depIdxs,
		MessageInfos:      file_grSim_Packet_proto_msgTypes,
	}.Build()
	File_grSim_Packet_proto = out.File
	file_grSim_Packet_proto_goTypes = nil
	file_grSim_Packet_proto_depIdxs = nil
}
