// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.1
// source: grSim_Replacement.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrSim_RobotReplacement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float64               `protobuf:"fixed64,1,req,name=x" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,2,req,name=y" json:"y,omitempty"`
	Dir           *float64               `protobuf:"fixed64,3,req,name=dir" json:"dir,omitempty"`
	Id            *uint32                `protobuf:"varint,4,req,name=id" json:"id,omitempty"`
	Yellowteam    *bool                  `protobuf:"varint,5,req,name=yellowteam" json:"yellowteam,omitempty"`
	Turnon        *bool                  `protobuf:"varint,6,opt,name=turnon" json:"turnon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrSim_RobotReplacement) Reset() {
	*x = GrSim_RobotReplacement{}
	mi := &file_grSim_Replacement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrSim_RobotReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrSim_RobotReplacement) ProtoMessage() {}

func (x *GrSim_RobotReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_grSim_Replacement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrSim_RobotReplacement.ProtoReflect.Descriptor instead.
func (*GrSim_RobotReplacement) Descriptor() ([]byte, []int) {
	return file_grSim_Replacement_proto_rawDescGZIP(), []int{0}
}

func (x *GrSim_RobotReplacement) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *GrSim_RobotReplacement) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *GrSim_RobotReplacement) GetDir() float64 {
	if x != nil && x.Dir != nil {
		return *x.Dir
	}
	return 0
}

func (x *GrSim_RobotReplacement) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GrSim_RobotReplacement) GetYellowteam() bool {
	if x != nil && x.Yellowteam != nil {
		return *x.Yellowteam
	}
	return false
}

func (x *GrSim_RobotReplacement) GetTurnon() bool {
	if x != nil && x.Turnon != nil {
		return *x.Turnon
	}
	return false
}

type GrSim_BallReplacement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float64               `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Vx            *float64               `protobuf:"fixed64,3,opt,name=vx" json:"vx,omitempty"`
	Vy            *float64               `protobuf:"fixed64,4,opt,name=vy" json:"vy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrSim_BallReplacement) Reset() {
	*x = GrSim_BallReplacement{}
	mi := &file_grSim_Replacement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrSim_BallReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrSim_BallReplacement) ProtoMessage() {}

func (x *GrSim_BallReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_grSim_Replacement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrSim_BallReplacement.ProtoReflect.Descriptor instead.
func (*GrSim_BallReplacement) Descriptor() ([]byte, []int) {
	return file_grSim_Replacement_proto_rawDescGZIP(), []int{1}
}

func (x *GrSim_BallReplacement) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *GrSim_BallReplacement) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *GrSim_BallReplacement) GetVx() float64 {
	if x != nil && x.Vx != nil {
		return *x.Vx
	}
	return 0
}

func (x *GrSim_BallReplacement) GetVy() float64 {
	if x != nil && x.Vy != nil {
		return *x.Vy
	}
	return 0
}

type GrSim_Replacement struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Ball          *GrSim_BallReplacement    `protobuf:"bytes,1,opt,name=ball" json:"ball,omitempty"`
	Robots        []*GrSim_RobotReplacement `protobuf:"bytes,2,rep,name=robots" json:"robots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrSim_Replacement) Reset() {
	*x = GrSim_Replacement{}
	mi := &file_grSim_Replacement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrSim_Replacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrSim_Replacement) ProtoMessage() {}

func (x *GrSim_Replacement) ProtoReflect() protoreflect.Message {
	mi := &file_grSim_Replacement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrSim_Replacement.ProtoReflect.Descriptor instead.
func (*GrSim_Replacement) Descriptor() ([]byte, []int) {
	return file_grSim_Replacement_proto_rawDescGZIP(), []int{2}
}

func (x *GrSim_Replacement) GetBall() *GrSim_BallReplacement {
	if x != nil {
		return x.Ball
	}
	return nil
}

func (x *GrSim_Replacement) GetRobots() []*GrSim_RobotReplacement {
	if x != nil {
		return x.Robots
	}
	return nil
}

var File_grSim_Replacement_proto protoreflect.FileDescriptor

const file_grSim_Replacement_proto_rawDesc = "" +
	"\n" +
	"\x17grSim_Replacement.proto\"\x8e\x01\n" +
	"\x16grSim_RobotReplacement\x12\f\n" +
	"\x01x\x18\x01 \x02(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x02(\x01R\x01y\x12\x10\n" +
	"\x03dir\x18\x03 \x02(\x01R\x03dir\x12\x0e\n" +
	"\x02id\x18\x04 \x02(\rR\x02id\x12\x1e\n" +
	"\n" +
	"yellowteam\x18\x05 \x02(\bR\n" +
	"yellowteam\x12\x16\n" +
	"\x06turnon\x18\x06 \x01(\bR\x06turnon\"S\n" +
	"\x15grSim_BallReplacement\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x0e\n" +
	"\x02vx\x18\x03 \x01(\x01R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x04 \x01(\x01R\x02vy\"p\n" +
	"\x11grSim_Replacement\x12*\n" +
	"\x04ball\x18\x01 \x01(\v2\x16.grSim_BallReplacementR\x04ball\x12/\n" +
	"\x06robots\x18\x02 \x03(\v2\x17.grSim_RobotReplacementR\x06robotsB-Z+github.com/Rione-SSL/RACOON-Pi/proto/pb_gen"

var (
	file_grSim_Replacement_proto_rawDescOnce sync.Once
	file_grSim_Replacement_proto_rawDescData []byte
)

func file_grSim_Replacement_proto_rawDescGZIP() []byte {
	file_grSim_Replacement_proto_rawDescOnce.Do(func() {
		file_grSim_Replacement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grSim_Replacement_proto_rawDesc), len(file_grSim_Replacement_proto_rawDesc)))
	})
	return file_grSim_Replacement_proto_rawDescData
}

var file_grSim_Replacement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grSim_Replacement_proto_goTypes = []any{
	(*GrSim_RobotReplacement)(nil), // 0: grSim_RobotReplacement
	(*GrSim_BallReplacement)(nil),  // 1: grSim_BallReplacement
	(*GrSim_Replacement)(nil),      // 2: grSim_Replacement
}
var file_grSim_Replacement_proto_depIdxs = []int32{
	1, // 0: grSim_Replacement.ball:type_name -> grSim_BallReplacement
	0, // 1: grSim_Replacement.robots:type_name -> grSim_RobotReplacement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grSim_Replacement_proto_init() }
func file_grSim_Replacement_proto_init() {
	if File_grSim_Replacement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grSim_Replacement_proto_rawDesc), len(file_grSim_Replacement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grSim_Replacement_proto_goTypes,
		DependencyIndexes: file_grSim_Replacement_proto_depIdxs,
		MessageInfos:      file_grSim_Replacement_proto_msgTypes,
	}.Build()
	File_grSim_Replacement_proto = out.File
	file_grSim_Replacement_proto_goTypes = nil
	file_grSim_Replacement_proto_depIdxs = nil
}
