// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pi_to_mw.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Robots_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotsStatus []*Robot_Status `protobuf:"bytes,1,rep,name=robots_status,json=robotsStatus,proto3" json:"robots_status,omitempty"`
}

func (x *Robots_Status) Reset() {
	*x = Robots_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_to_mw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Robots_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robots_Status) ProtoMessage() {}

func (x *Robots_Status) ProtoReflect() protoreflect.Message {
	mi := &file_pi_to_mw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robots_Status.ProtoReflect.Descriptor instead.
func (*Robots_Status) Descriptor() ([]byte, []int) {
	return file_pi_to_mw_proto_rawDescGZIP(), []int{0}
}

func (x *Robots_Status) GetRobotsStatus() []*Robot_Status {
	if x != nil {
		return x.RobotsStatus
	}
	return nil
}

type Robot_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId        uint32 `protobuf:"varint,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Infrared       bool   `protobuf:"varint,2,opt,name=infrared,proto3" json:"infrared,omitempty"`
	BatteryVoltage uint32 `protobuf:"varint,3,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`
	CapPower       uint32 `protobuf:"varint,4,opt,name=cap_power,json=capPower,proto3" json:"cap_power,omitempty"`
}

func (x *Robot_Status) Reset() {
	*x = Robot_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_to_mw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Robot_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robot_Status) ProtoMessage() {}

func (x *Robot_Status) ProtoReflect() protoreflect.Message {
	mi := &file_pi_to_mw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robot_Status.ProtoReflect.Descriptor instead.
func (*Robot_Status) Descriptor() ([]byte, []int) {
	return file_pi_to_mw_proto_rawDescGZIP(), []int{1}
}

func (x *Robot_Status) GetRobotId() uint32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Robot_Status) GetInfrared() bool {
	if x != nil {
		return x.Infrared
	}
	return false
}

func (x *Robot_Status) GetBatteryVoltage() uint32 {
	if x != nil {
		return x.BatteryVoltage
	}
	return 0
}

func (x *Robot_Status) GetCapPower() uint32 {
	if x != nil {
		return x.CapPower
	}
	return 0
}

type ImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_to_mw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_to_mw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_pi_to_mw_proto_rawDescGZIP(), []int{2}
}

func (x *ImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pi_to_mw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pi_to_mw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_pi_to_mw_proto_rawDescGZIP(), []int{3}
}

func (x *ImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pi_to_mw_proto protoreflect.FileDescriptor

var file_pi_to_mw_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x69, 0x5f, 0x74, 0x6f, 0x5f, 0x6d, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x0d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x32, 0x0a, 0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x5f,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x72, 0x65, 0x64, 0x12, 0x27, 0x0a,
	0x0f, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x5f, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x56,
	0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x5f, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x70, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x41, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x0d, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x69, 0x6f, 0x6e, 0x65, 0x2f, 0x73, 0x73, 0x6c, 0x2d,
	0x52, 0x41, 0x43, 0x4f, 0x4f, 0x4e, 0x2d, 0x50, 0x69, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pi_to_mw_proto_rawDescOnce sync.Once
	file_pi_to_mw_proto_rawDescData = file_pi_to_mw_proto_rawDesc
)

func file_pi_to_mw_proto_rawDescGZIP() []byte {
	file_pi_to_mw_proto_rawDescOnce.Do(func() {
		file_pi_to_mw_proto_rawDescData = protoimpl.X.CompressGZIP(file_pi_to_mw_proto_rawDescData)
	})
	return file_pi_to_mw_proto_rawDescData
}

var file_pi_to_mw_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pi_to_mw_proto_goTypes = []interface{}{
	(*Robots_Status)(nil), // 0: Robots_Status
	(*Robot_Status)(nil),  // 1: Robot_Status
	(*ImageRequest)(nil),  // 2: ImageRequest
	(*ImageResponse)(nil), // 3: ImageResponse
}
var file_pi_to_mw_proto_depIdxs = []int32{
	1, // 0: Robots_Status.robots_status:type_name -> Robot_Status
	2, // 1: ImageService.ClientStream:input_type -> ImageRequest
	3, // 2: ImageService.ClientStream:output_type -> ImageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pi_to_mw_proto_init() }
func file_pi_to_mw_proto_init() {
	if File_pi_to_mw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pi_to_mw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Robots_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_to_mw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Robot_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_to_mw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pi_to_mw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pi_to_mw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pi_to_mw_proto_goTypes,
		DependencyIndexes: file_pi_to_mw_proto_depIdxs,
		MessageInfos:      file_pi_to_mw_proto_msgTypes,
	}.Build()
	File_pi_to_mw_proto = out.File
	file_pi_to_mw_proto_rawDesc = nil
	file_pi_to_mw_proto_goTypes = nil
	file_pi_to_mw_proto_depIdxs = nil
}
