// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.1
// source: ssl_gc_state.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Type int32

const (
	Command_UNKNOWN        Command_Type = 0
	Command_HALT           Command_Type = 1
	Command_STOP           Command_Type = 2
	Command_NORMAL_START   Command_Type = 3
	Command_FORCE_START    Command_Type = 4
	Command_DIRECT         Command_Type = 5
	Command_INDIRECT       Command_Type = 6
	Command_KICKOFF        Command_Type = 7
	Command_PENALTY        Command_Type = 8
	Command_TIMEOUT        Command_Type = 9
	Command_BALL_PLACEMENT Command_Type = 10
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "HALT",
		2:  "STOP",
		3:  "NORMAL_START",
		4:  "FORCE_START",
		5:  "DIRECT",
		6:  "INDIRECT",
		7:  "KICKOFF",
		8:  "PENALTY",
		9:  "TIMEOUT",
		10: "BALL_PLACEMENT",
	}
	Command_Type_value = map[string]int32{
		"UNKNOWN":        0,
		"HALT":           1,
		"STOP":           2,
		"NORMAL_START":   3,
		"FORCE_START":    4,
		"DIRECT":         5,
		"INDIRECT":       6,
		"KICKOFF":        7,
		"PENALTY":        8,
		"TIMEOUT":        9,
		"BALL_PLACEMENT": 10,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_ssl_gc_state_proto_enumTypes[0].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_ssl_gc_state_proto_enumTypes[0]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Command_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Command_Type(num)
	return nil
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{3, 0}
}

type GameState_Type int32

const (
	GameState_UNKNOWN        GameState_Type = 0
	GameState_HALT           GameState_Type = 1
	GameState_STOP           GameState_Type = 2
	GameState_RUNNING        GameState_Type = 3
	GameState_FREE_KICK      GameState_Type = 4
	GameState_KICKOFF        GameState_Type = 5
	GameState_PENALTY        GameState_Type = 6
	GameState_TIMEOUT        GameState_Type = 7
	GameState_BALL_PLACEMENT GameState_Type = 8
)

// Enum value maps for GameState_Type.
var (
	GameState_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "HALT",
		2: "STOP",
		3: "RUNNING",
		4: "FREE_KICK",
		5: "KICKOFF",
		6: "PENALTY",
		7: "TIMEOUT",
		8: "BALL_PLACEMENT",
	}
	GameState_Type_value = map[string]int32{
		"UNKNOWN":        0,
		"HALT":           1,
		"STOP":           2,
		"RUNNING":        3,
		"FREE_KICK":      4,
		"KICKOFF":        5,
		"PENALTY":        6,
		"TIMEOUT":        7,
		"BALL_PLACEMENT": 8,
	}
)

func (x GameState_Type) Enum() *GameState_Type {
	p := new(GameState_Type)
	*p = x
	return p
}

func (x GameState_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_ssl_gc_state_proto_enumTypes[1].Descriptor()
}

func (GameState_Type) Type() protoreflect.EnumType {
	return &file_ssl_gc_state_proto_enumTypes[1]
}

func (x GameState_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GameState_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GameState_Type(num)
	return nil
}

// Deprecated: Use GameState_Type.Descriptor instead.
func (GameState_Type) EnumDescriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{4, 0}
}

type YellowCard struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CausedByGameEvent *GameEvent             `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	TimeRemaining     *durationpb.Duration   `protobuf:"bytes,3,opt,name=time_remaining,json=timeRemaining" json:"time_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *YellowCard) Reset() {
	*x = YellowCard{}
	mi := &file_ssl_gc_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YellowCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YellowCard) ProtoMessage() {}

func (x *YellowCard) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YellowCard.ProtoReflect.Descriptor instead.
func (*YellowCard) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{0}
}

func (x *YellowCard) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *YellowCard) GetCausedByGameEvent() *GameEvent {
	if x != nil {
		return x.CausedByGameEvent
	}
	return nil
}

func (x *YellowCard) GetTimeRemaining() *durationpb.Duration {
	if x != nil {
		return x.TimeRemaining
	}
	return nil
}

type RedCard struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CausedByGameEvent *GameEvent             `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RedCard) Reset() {
	*x = RedCard{}
	mi := &file_ssl_gc_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedCard) ProtoMessage() {}

func (x *RedCard) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedCard.ProtoReflect.Descriptor instead.
func (*RedCard) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{1}
}

func (x *RedCard) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RedCard) GetCausedByGameEvent() *GameEvent {
	if x != nil {
		return x.CausedByGameEvent
	}
	return nil
}

type Foul struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CausedByGameEvent *GameEvent             `protobuf:"bytes,2,opt,name=caused_by_game_event,json=causedByGameEvent" json:"caused_by_game_event,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Foul) Reset() {
	*x = Foul{}
	mi := &file_ssl_gc_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foul) ProtoMessage() {}

func (x *Foul) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foul.ProtoReflect.Descriptor instead.
func (*Foul) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{2}
}

func (x *Foul) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Foul) GetCausedByGameEvent() *GameEvent {
	if x != nil {
		return x.CausedByGameEvent
	}
	return nil
}

func (x *Foul) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Command_Type          `protobuf:"varint,1,req,name=type,enum=Command_Type" json:"type,omitempty"`
	ForTeam       *Team                  `protobuf:"varint,2,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_ssl_gc_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetType() Command_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Command_UNKNOWN
}

func (x *Command) GetForTeam() Team {
	if x != nil && x.ForTeam != nil {
		return *x.ForTeam
	}
	return Team_UNKNOWN
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *GameState_Type        `protobuf:"varint,1,req,name=type,enum=GameState_Type" json:"type,omitempty"`
	ForTeam       *Team                  `protobuf:"varint,2,opt,name=for_team,json=forTeam,enum=Team" json:"for_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_ssl_gc_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{4}
}

func (x *GameState) GetType() GameState_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return GameState_UNKNOWN
}

func (x *GameState) GetForTeam() Team {
	if x != nil && x.ForTeam != nil {
		return *x.ForTeam
	}
	return Team_UNKNOWN
}

type Proposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp when the game event proposal occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// The proposed game event.
	GameEvent     *GameEvent `protobuf:"bytes,2,opt,name=game_event,json=gameEvent" json:"game_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_ssl_gc_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{5}
}

func (x *Proposal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Proposal) GetGameEvent() *GameEvent {
	if x != nil {
		return x.GameEvent
	}
	return nil
}

type ProposalGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of proposals in this group
	Proposals []*Proposal `protobuf:"bytes,1,rep,name=proposals" json:"proposals,omitempty"`
	// Whether the proposal group was accepted
	Accepted      *bool `protobuf:"varint,2,opt,name=accepted" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalGroup) Reset() {
	*x = ProposalGroup{}
	mi := &file_ssl_gc_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalGroup) ProtoMessage() {}

func (x *ProposalGroup) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalGroup.ProtoReflect.Descriptor instead.
func (*ProposalGroup) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{6}
}

func (x *ProposalGroup) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *ProposalGroup) GetAccepted() bool {
	if x != nil && x.Accepted != nil {
		return *x.Accepted
	}
	return false
}

type TeamInfo struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Name                         *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Goals                        *int32                 `protobuf:"varint,2,opt,name=goals" json:"goals,omitempty"`
	Goalkeeper                   *int32                 `protobuf:"varint,3,opt,name=goalkeeper" json:"goalkeeper,omitempty"`
	YellowCards                  []*YellowCard          `protobuf:"bytes,4,rep,name=yellow_cards,json=yellowCards" json:"yellow_cards,omitempty"`
	RedCards                     []*RedCard             `protobuf:"bytes,5,rep,name=red_cards,json=redCards" json:"red_cards,omitempty"`
	TimeoutsLeft                 *int32                 `protobuf:"varint,6,opt,name=timeouts_left,json=timeoutsLeft" json:"timeouts_left,omitempty"`
	TimeoutTimeLeft              *durationpb.Duration   `protobuf:"bytes,7,opt,name=timeout_time_left,json=timeoutTimeLeft" json:"timeout_time_left,omitempty"`
	OnPositiveHalf               *bool                  `protobuf:"varint,8,opt,name=on_positive_half,json=onPositiveHalf" json:"on_positive_half,omitempty"`
	Fouls                        []*Foul                `protobuf:"bytes,9,rep,name=fouls" json:"fouls,omitempty"`
	BallPlacementFailures        *int32                 `protobuf:"varint,10,opt,name=ball_placement_failures,json=ballPlacementFailures" json:"ball_placement_failures,omitempty"`
	BallPlacementFailuresReached *bool                  `protobuf:"varint,11,opt,name=ball_placement_failures_reached,json=ballPlacementFailuresReached" json:"ball_placement_failures_reached,omitempty"`
	CanPlaceBall                 *bool                  `protobuf:"varint,12,opt,name=can_place_ball,json=canPlaceBall" json:"can_place_ball,omitempty"`
	MaxAllowedBots               *int32                 `protobuf:"varint,13,opt,name=max_allowed_bots,json=maxAllowedBots" json:"max_allowed_bots,omitempty"`
	RequestsBotSubstitutionSince *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=requests_bot_substitution_since,json=requestsBotSubstitutionSince" json:"requests_bot_substitution_since,omitempty"`
	RequestsTimeoutSince         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=requests_timeout_since,json=requestsTimeoutSince" json:"requests_timeout_since,omitempty"`
	RequestsEmergencyStopSince   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=requests_emergency_stop_since,json=requestsEmergencyStopSince" json:"requests_emergency_stop_since,omitempty"`
	ChallengeFlags               *int32                 `protobuf:"varint,17,opt,name=challenge_flags,json=challengeFlags" json:"challenge_flags,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TeamInfo) Reset() {
	*x = TeamInfo{}
	mi := &file_ssl_gc_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInfo) ProtoMessage() {}

func (x *TeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInfo.ProtoReflect.Descriptor instead.
func (*TeamInfo) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{7}
}

func (x *TeamInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TeamInfo) GetGoals() int32 {
	if x != nil && x.Goals != nil {
		return *x.Goals
	}
	return 0
}

func (x *TeamInfo) GetGoalkeeper() int32 {
	if x != nil && x.Goalkeeper != nil {
		return *x.Goalkeeper
	}
	return 0
}

func (x *TeamInfo) GetYellowCards() []*YellowCard {
	if x != nil {
		return x.YellowCards
	}
	return nil
}

func (x *TeamInfo) GetRedCards() []*RedCard {
	if x != nil {
		return x.RedCards
	}
	return nil
}

func (x *TeamInfo) GetTimeoutsLeft() int32 {
	if x != nil && x.TimeoutsLeft != nil {
		return *x.TimeoutsLeft
	}
	return 0
}

func (x *TeamInfo) GetTimeoutTimeLeft() *durationpb.Duration {
	if x != nil {
		return x.TimeoutTimeLeft
	}
	return nil
}

func (x *TeamInfo) GetOnPositiveHalf() bool {
	if x != nil && x.OnPositiveHalf != nil {
		return *x.OnPositiveHalf
	}
	return false
}

func (x *TeamInfo) GetFouls() []*Foul {
	if x != nil {
		return x.Fouls
	}
	return nil
}

func (x *TeamInfo) GetBallPlacementFailures() int32 {
	if x != nil && x.BallPlacementFailures != nil {
		return *x.BallPlacementFailures
	}
	return 0
}

func (x *TeamInfo) GetBallPlacementFailuresReached() bool {
	if x != nil && x.BallPlacementFailuresReached != nil {
		return *x.BallPlacementFailuresReached
	}
	return false
}

func (x *TeamInfo) GetCanPlaceBall() bool {
	if x != nil && x.CanPlaceBall != nil {
		return *x.CanPlaceBall
	}
	return false
}

func (x *TeamInfo) GetMaxAllowedBots() int32 {
	if x != nil && x.MaxAllowedBots != nil {
		return *x.MaxAllowedBots
	}
	return 0
}

func (x *TeamInfo) GetRequestsBotSubstitutionSince() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestsBotSubstitutionSince
	}
	return nil
}

func (x *TeamInfo) GetRequestsTimeoutSince() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestsTimeoutSince
	}
	return nil
}

func (x *TeamInfo) GetRequestsEmergencyStopSince() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestsEmergencyStopSince
	}
	return nil
}

func (x *TeamInfo) GetChallengeFlags() int32 {
	if x != nil && x.ChallengeFlags != nil {
		return *x.ChallengeFlags
	}
	return 0
}

type State struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Stage                      *Referee_Stage         `protobuf:"varint,1,opt,name=stage,enum=Referee_Stage" json:"stage,omitempty"`
	Command                    *Command               `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	GameState                  *GameState             `protobuf:"bytes,19,opt,name=game_state,json=gameState" json:"game_state,omitempty"`
	StageTimeElapsed           *durationpb.Duration   `protobuf:"bytes,4,opt,name=stage_time_elapsed,json=stageTimeElapsed" json:"stage_time_elapsed,omitempty"`
	StageTimeLeft              *durationpb.Duration   `protobuf:"bytes,5,opt,name=stage_time_left,json=stageTimeLeft" json:"stage_time_left,omitempty"`
	MatchTimeStart             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=match_time_start,json=matchTimeStart" json:"match_time_start,omitempty"`
	TeamState                  map[string]*TeamInfo   `protobuf:"bytes,8,rep,name=team_state,json=teamState" json:"team_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PlacementPos               *Vector2               `protobuf:"bytes,9,opt,name=placement_pos,json=placementPos" json:"placement_pos,omitempty"`
	NextCommand                *Command               `protobuf:"bytes,10,opt,name=next_command,json=nextCommand" json:"next_command,omitempty"`
	CurrentActionTimeRemaining *durationpb.Duration   `protobuf:"bytes,12,opt,name=current_action_time_remaining,json=currentActionTimeRemaining" json:"current_action_time_remaining,omitempty"`
	GameEvents                 []*GameEvent           `protobuf:"bytes,13,rep,name=game_events,json=gameEvents" json:"game_events,omitempty"`
	ProposalGroups             []*ProposalGroup       `protobuf:"bytes,14,rep,name=proposal_groups,json=proposalGroups" json:"proposal_groups,omitempty"`
	Division                   *Division              `protobuf:"varint,15,opt,name=division,enum=Division" json:"division,omitempty"`
	AutoContinue               *bool                  `protobuf:"varint,16,opt,name=auto_continue,json=autoContinue" json:"auto_continue,omitempty"`
	FirstKickoffTeam           *Team                  `protobuf:"varint,17,opt,name=first_kickoff_team,json=firstKickoffTeam,enum=Team" json:"first_kickoff_team,omitempty"`
	MatchType                  *MatchType             `protobuf:"varint,18,opt,name=match_type,json=matchType,enum=MatchType" json:"match_type,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_ssl_gc_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_gc_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_ssl_gc_state_proto_rawDescGZIP(), []int{8}
}

func (x *State) GetStage() Referee_Stage {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return Referee_NORMAL_FIRST_HALF_PRE
}

func (x *State) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *State) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *State) GetStageTimeElapsed() *durationpb.Duration {
	if x != nil {
		return x.StageTimeElapsed
	}
	return nil
}

func (x *State) GetStageTimeLeft() *durationpb.Duration {
	if x != nil {
		return x.StageTimeLeft
	}
	return nil
}

func (x *State) GetMatchTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchTimeStart
	}
	return nil
}

func (x *State) GetTeamState() map[string]*TeamInfo {
	if x != nil {
		return x.TeamState
	}
	return nil
}

func (x *State) GetPlacementPos() *Vector2 {
	if x != nil {
		return x.PlacementPos
	}
	return nil
}

func (x *State) GetNextCommand() *Command {
	if x != nil {
		return x.NextCommand
	}
	return nil
}

func (x *State) GetCurrentActionTimeRemaining() *durationpb.Duration {
	if x != nil {
		return x.CurrentActionTimeRemaining
	}
	return nil
}

func (x *State) GetGameEvents() []*GameEvent {
	if x != nil {
		return x.GameEvents
	}
	return nil
}

func (x *State) GetProposalGroups() []*ProposalGroup {
	if x != nil {
		return x.ProposalGroups
	}
	return nil
}

func (x *State) GetDivision() Division {
	if x != nil && x.Division != nil {
		return *x.Division
	}
	return Division_DIV_UNKNOWN
}

func (x *State) GetAutoContinue() bool {
	if x != nil && x.AutoContinue != nil {
		return *x.AutoContinue
	}
	return false
}

func (x *State) GetFirstKickoffTeam() Team {
	if x != nil && x.FirstKickoffTeam != nil {
		return *x.FirstKickoffTeam
	}
	return Team_UNKNOWN
}

func (x *State) GetMatchType() MatchType {
	if x != nil && x.MatchType != nil {
		return *x.MatchType
	}
	return MatchType_UNKNOWN_MATCH
}

var File_ssl_gc_state_proto protoreflect.FileDescriptor

const file_ssl_gc_state_proto_rawDesc = "" +
	"\n" +
	"\x12ssl_gc_state.proto\x1a\x13ssl_gc_common.proto\x1a\x15ssl_gc_geometry.proto\x1a\x17ssl_gc_game_event.proto\x1a\x1cssl_gc_referee_message.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\n" +
	"YellowCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12;\n" +
	"\x14caused_by_game_event\x18\x02 \x01(\v2\n" +
	".GameEventR\x11causedByGameEvent\x12@\n" +
	"\x0etime_remaining\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rtimeRemaining\"V\n" +
	"\aRedCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12;\n" +
	"\x14caused_by_game_event\x18\x02 \x01(\v2\n" +
	".GameEventR\x11causedByGameEvent\"\x8d\x01\n" +
	"\x04Foul\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12;\n" +
	"\x14caused_by_game_event\x18\x02 \x01(\v2\n" +
	".GameEventR\x11causedByGameEvent\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf0\x01\n" +
	"\aCommand\x12!\n" +
	"\x04type\x18\x01 \x02(\x0e2\r.Command.TypeR\x04type\x12 \n" +
	"\bfor_team\x18\x02 \x01(\x0e2\x05.TeamR\aforTeam\"\x9f\x01\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04HALT\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\x10\n" +
	"\fNORMAL_START\x10\x03\x12\x0f\n" +
	"\vFORCE_START\x10\x04\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x05\x12\f\n" +
	"\bINDIRECT\x10\x06\x12\v\n" +
	"\aKICKOFF\x10\a\x12\v\n" +
	"\aPENALTY\x10\b\x12\v\n" +
	"\aTIMEOUT\x10\t\x12\x12\n" +
	"\x0eBALL_PLACEMENT\x10\n" +
	"\"\xd2\x01\n" +
	"\tGameState\x12#\n" +
	"\x04type\x18\x01 \x02(\x0e2\x0f.GameState.TypeR\x04type\x12 \n" +
	"\bfor_team\x18\x02 \x01(\x0e2\x05.TeamR\aforTeam\"~\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04HALT\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\r\n" +
	"\tFREE_KICK\x10\x04\x12\v\n" +
	"\aKICKOFF\x10\x05\x12\v\n" +
	"\aPENALTY\x10\x06\x12\v\n" +
	"\aTIMEOUT\x10\a\x12\x12\n" +
	"\x0eBALL_PLACEMENT\x10\b\"o\n" +
	"\bProposal\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\n" +
	"game_event\x18\x02 \x01(\v2\n" +
	".GameEventR\tgameEvent\"T\n" +
	"\rProposalGroup\x12'\n" +
	"\tproposals\x18\x01 \x03(\v2\t.ProposalR\tproposals\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"\xea\x06\n" +
	"\bTeamInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05goals\x18\x02 \x01(\x05R\x05goals\x12\x1e\n" +
	"\n" +
	"goalkeeper\x18\x03 \x01(\x05R\n" +
	"goalkeeper\x12.\n" +
	"\fyellow_cards\x18\x04 \x03(\v2\v.YellowCardR\vyellowCards\x12%\n" +
	"\tred_cards\x18\x05 \x03(\v2\b.RedCardR\bredCards\x12#\n" +
	"\rtimeouts_left\x18\x06 \x01(\x05R\ftimeoutsLeft\x12E\n" +
	"\x11timeout_time_left\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0ftimeoutTimeLeft\x12(\n" +
	"\x10on_positive_half\x18\b \x01(\bR\x0eonPositiveHalf\x12\x1b\n" +
	"\x05fouls\x18\t \x03(\v2\x05.FoulR\x05fouls\x126\n" +
	"\x17ball_placement_failures\x18\n" +
	" \x01(\x05R\x15ballPlacementFailures\x12E\n" +
	"\x1fball_placement_failures_reached\x18\v \x01(\bR\x1cballPlacementFailuresReached\x12$\n" +
	"\x0ecan_place_ball\x18\f \x01(\bR\fcanPlaceBall\x12(\n" +
	"\x10max_allowed_bots\x18\r \x01(\x05R\x0emaxAllowedBots\x12a\n" +
	"\x1frequests_bot_substitution_since\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x1crequestsBotSubstitutionSince\x12P\n" +
	"\x16requests_timeout_since\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x14requestsTimeoutSince\x12]\n" +
	"\x1drequests_emergency_stop_since\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x1arequestsEmergencyStopSince\x12'\n" +
	"\x0fchallenge_flags\x18\x11 \x01(\x05R\x0echallengeFlags\"\x99\a\n" +
	"\x05State\x12$\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x0e.Referee.StageR\x05stage\x12\"\n" +
	"\acommand\x18\x02 \x01(\v2\b.CommandR\acommand\x12)\n" +
	"\n" +
	"game_state\x18\x13 \x01(\v2\n" +
	".GameStateR\tgameState\x12G\n" +
	"\x12stage_time_elapsed\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x10stageTimeElapsed\x12A\n" +
	"\x0fstage_time_left\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rstageTimeLeft\x12D\n" +
	"\x10match_time_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ematchTimeStart\x124\n" +
	"\n" +
	"team_state\x18\b \x03(\v2\x15.State.TeamStateEntryR\tteamState\x12-\n" +
	"\rplacement_pos\x18\t \x01(\v2\b.Vector2R\fplacementPos\x12+\n" +
	"\fnext_command\x18\n" +
	" \x01(\v2\b.CommandR\vnextCommand\x12\\\n" +
	"\x1dcurrent_action_time_remaining\x18\f \x01(\v2\x19.google.protobuf.DurationR\x1acurrentActionTimeRemaining\x12+\n" +
	"\vgame_events\x18\r \x03(\v2\n" +
	".GameEventR\n" +
	"gameEvents\x127\n" +
	"\x0fproposal_groups\x18\x0e \x03(\v2\x0e.ProposalGroupR\x0eproposalGroups\x12%\n" +
	"\bdivision\x18\x0f \x01(\x0e2\t.DivisionR\bdivision\x12#\n" +
	"\rauto_continue\x18\x10 \x01(\bR\fautoContinue\x123\n" +
	"\x12first_kickoff_team\x18\x11 \x01(\x0e2\x05.TeamR\x10firstKickoffTeam\x12)\n" +
	"\n" +
	"match_type\x18\x12 \x01(\x0e2\n" +
	".MatchTypeR\tmatchType\x1aG\n" +
	"\x0eTeamStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.TeamInfoR\x05value:\x028\x01B-Z+github.com/Rione-SSL/RACOON-Pi/proto/pb_gen"

var (
	file_ssl_gc_state_proto_rawDescOnce sync.Once
	file_ssl_gc_state_proto_rawDescData []byte
)

func file_ssl_gc_state_proto_rawDescGZIP() []byte {
	file_ssl_gc_state_proto_rawDescOnce.Do(func() {
		file_ssl_gc_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ssl_gc_state_proto_rawDesc), len(file_ssl_gc_state_proto_rawDesc)))
	})
	return file_ssl_gc_state_proto_rawDescData
}

var file_ssl_gc_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ssl_gc_state_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ssl_gc_state_proto_goTypes = []any{
	(Command_Type)(0),             // 0: Command.Type
	(GameState_Type)(0),           // 1: GameState.Type
	(*YellowCard)(nil),            // 2: YellowCard
	(*RedCard)(nil),               // 3: RedCard
	(*Foul)(nil),                  // 4: Foul
	(*Command)(nil),               // 5: Command
	(*GameState)(nil),             // 6: GameState
	(*Proposal)(nil),              // 7: Proposal
	(*ProposalGroup)(nil),         // 8: ProposalGroup
	(*TeamInfo)(nil),              // 9: TeamInfo
	(*State)(nil),                 // 10: State
	nil,                           // 11: State.TeamStateEntry
	(*GameEvent)(nil),             // 12: GameEvent
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(Team)(0),                     // 15: Team
	(Referee_Stage)(0),            // 16: Referee.Stage
	(*Vector2)(nil),               // 17: Vector2
	(Division)(0),                 // 18: Division
	(MatchType)(0),                // 19: MatchType
}
var file_ssl_gc_state_proto_depIdxs = []int32{
	12, // 0: YellowCard.caused_by_game_event:type_name -> GameEvent
	13, // 1: YellowCard.time_remaining:type_name -> google.protobuf.Duration
	12, // 2: RedCard.caused_by_game_event:type_name -> GameEvent
	12, // 3: Foul.caused_by_game_event:type_name -> GameEvent
	14, // 4: Foul.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: Command.type:type_name -> Command.Type
	15, // 6: Command.for_team:type_name -> Team
	1,  // 7: GameState.type:type_name -> GameState.Type
	15, // 8: GameState.for_team:type_name -> Team
	14, // 9: Proposal.timestamp:type_name -> google.protobuf.Timestamp
	12, // 10: Proposal.game_event:type_name -> GameEvent
	7,  // 11: ProposalGroup.proposals:type_name -> Proposal
	2,  // 12: TeamInfo.yellow_cards:type_name -> YellowCard
	3,  // 13: TeamInfo.red_cards:type_name -> RedCard
	13, // 14: TeamInfo.timeout_time_left:type_name -> google.protobuf.Duration
	4,  // 15: TeamInfo.fouls:type_name -> Foul
	14, // 16: TeamInfo.requests_bot_substitution_since:type_name -> google.protobuf.Timestamp
	14, // 17: TeamInfo.requests_timeout_since:type_name -> google.protobuf.Timestamp
	14, // 18: TeamInfo.requests_emergency_stop_since:type_name -> google.protobuf.Timestamp
	16, // 19: State.stage:type_name -> Referee.Stage
	5,  // 20: State.command:type_name -> Command
	6,  // 21: State.game_state:type_name -> GameState
	13, // 22: State.stage_time_elapsed:type_name -> google.protobuf.Duration
	13, // 23: State.stage_time_left:type_name -> google.protobuf.Duration
	14, // 24: State.match_time_start:type_name -> google.protobuf.Timestamp
	11, // 25: State.team_state:type_name -> State.TeamStateEntry
	17, // 26: State.placement_pos:type_name -> Vector2
	5,  // 27: State.next_command:type_name -> Command
	13, // 28: State.current_action_time_remaining:type_name -> google.protobuf.Duration
	12, // 29: State.game_events:type_name -> GameEvent
	8,  // 30: State.proposal_groups:type_name -> ProposalGroup
	18, // 31: State.division:type_name -> Division
	15, // 32: State.first_kickoff_team:type_name -> Team
	19, // 33: State.match_type:type_name -> MatchType
	9,  // 34: State.TeamStateEntry.value:type_name -> TeamInfo
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_ssl_gc_state_proto_init() }
func file_ssl_gc_state_proto_init() {
	if File_ssl_gc_state_proto != nil {
		return
	}
	file_ssl_gc_common_proto_init()
	file_ssl_gc_geometry_proto_init()
	file_ssl_gc_game_event_proto_init()
	file_ssl_gc_referee_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ssl_gc_state_proto_rawDesc), len(file_ssl_gc_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ssl_gc_state_proto_goTypes,
		DependencyIndexes: file_ssl_gc_state_proto_depIdxs,
		EnumInfos:         file_ssl_gc_state_proto_enumTypes,
		MessageInfos:      file_ssl_gc_state_proto_msgTypes,
	}.Build()
	File_ssl_gc_state_proto = out.File
	file_ssl_gc_state_proto_goTypes = nil
	file_ssl_gc_state_proto_depIdxs = nil
}
